"use client";

import { motion } from "framer-motion";
import { Icon, type IconName } from "@/components/ui/Icon";
import { Section, SectionContainer, SectionHeader, SectionRule } from "./Section";

const features: { title: string; description: string; icon: IconName }[] = [
  {
    title: "IMDb verified ratings",
    description:
      "Every movie we recommend has been vetted against IMDb's community ratings. We only surface films that meet our quality threshold.",
    icon: "badge-check",
  },
  {
    title: "Streams where you already are",
    description:
      "We tell you exactly where each pick is streaming — Netflix, Prime Video, Max, Apple TV+ and more — with a direct link so you can start watching in one tap.",
    icon: "bolt",
  },
  {
    title: "Zero spam promise",
    description:
      "One email per week, every Friday. No noise, and we'll never sell your data. Unsubscribe in one click at any time.",
    icon: "shield",
  },
  {
    title: "Human curated",
    description:
      "Our picks aren't generated by a cold algorithm. We combine data with human taste to find movies that actually deliver great storytelling.",
    icon: "heart",
  },
  {
    title: "Beautifully designed",
    description:
      "Our emails are crafted to be a joy to read. Rich poster images, clear ratings, genre tags, and trailers — everything at a glance.",
    icon: "sparkles",
  },
  {
    title: "Free to join",
    description:
      "The weekly newsletter is free, full stop. We're movie lovers building this for movie lovers — start getting great picks without paying a thing.",
    icon: "gift",
  },
];

export function WhyRecon() {
  return (
    <Section id="why-recon" className="border-t border-border/60">
      <SectionRule />
      <div aria-hidden className="absolute right-0 top-1/4 size-[31rem] rounded-full bg-accent-500/4 blur-[150px]" />

      <SectionContainer>
        <SectionHeader
          eyebrow="Built for trust"
          title="Why choose Recon"
          lead="We believe your inbox should feel like a gift, not a chore. Here's what makes Recon different."
        />

        <div className="grid gap-3 sm:grid-cols-2 sm:gap-5 lg:grid-cols-3">
          {features.map((feature, i) => (
            <motion.div
              key={feature.title}
              initial={{ opacity: 0, y: 24 }}
              whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true, amount: 0.2 }}
              transition={{ delay: (i % 3) * 0.08, duration: 0.45, ease: "easeOut" }}
              // Phones: compact icon-left rows. sm+: stacked cards.
              className="group flex gap-4 rounded-2xl border border-border bg-surface p-4 transition-colors duration-300 hover:border-accent-500/30 sm:block sm:p-7"
            >
              <div className="flex size-11 shrink-0 items-center justify-center rounded-xl border border-accent-150 bg-accent-50 text-accent-500 transition-colors group-hover:bg-accent-100 sm:mb-4">
                <Icon name={feature.icon} className="size-[22px]" weight={1.5} />
              </div>
              <div className="min-w-0">
                <h3 className="mb-1 text-base font-semibold text-foreground sm:mb-2 sm:text-lg">
                  {feature.title}
                </h3>
                <p className="text-sm leading-relaxed text-muted">{feature.description}</p>
              </div>
            </motion.div>
          ))}
        </div>
      </SectionContainer>
    </Section>
  );
}
